### ISSUE TITLE
build: webfont task custom css template outputs double @font-face

### ISSUE THREAD

**Issue by ctalkington** [FlagshipWP/compass#58]
not sure if this is desired but i tend to end up with:

cc @robneu 

```scss
@font-face {
	font-family: "siteicons";
	src: url("fonts/siteicons.eot");
	font-weight: normal;
	font-style: normal;
}

@font-face {
	font-family: "siteicons";
	src: url("fonts/siteicons.eot");
	src: url("fonts/siteicons.eot?#iefix") format("embedded-opentype"),
		url("data:application/x-font-woff;charset=utf-8;base64,d09GRgABAAAAACGsAAoAAAAANtQAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABPUy8yAAAA9AAAAEMAAABWQLtKx2NtYXAAAAE4AAAAOgAAAUrieRC2Z2x5ZgAAAXQAABrvAAAq8HKtSjxoZWFkAAAcZAAAADAAAAA2BATvdmhoZWEAAByUAAAAIAAAACQD+AIiaG10eAAAHLQAAAASAAABoM4YAABsb2NhAAAcyAAAANIAAADSHNYSMG1heHAAAB2cAAAAHwAAACABewCSbmFtZQAAHbwAAAEpAAACItVReEpwb3N0AAAe6AAAAsEAAASAg/jxeXicY2Bk/M04gYGVgYOBnzGNgYHBHUp/ZZBkaGFgYGJgZWbACgLSXFMYHD4yfkxnPPD/AIMe4wEGB6AwI0gOAMUHDAQAeJxjYGBgZoBgGQZGBhBwAfIYwXwWBg0gzQakGRmYGBg+pv//D1LwkRFE8zNA1QMBIxvDiAcA4LwHHgAAeJzFWmtw49Z1xgEIgA8QJEACIEUKfBNaQqIovrAr7Urc9WbfdmxnKdfZJtlVknoipk4fnsR2UofxrJ2kmWaStNqk46ZdJz8yXY3bTFO37kw7kdskddyZ9JFK02T6I5OZTjvZtn/6mD65PeeCpCjH/yuRuMDFBXDveXznOwfkAhx370fwOnye07gC9xD3Do6rqFAqVp2qZNnQana9btWrFmWptQ6WKcmStw6OCjJ+/NM2dm9A16mD0+lWsZGrOMrMQRdHtpo2Pw9J7JDr0ME7wAuV+yvd99YCAr/wntXaZkGSKmLdkGSlKAlhEWRN+Ur6RCqTB1guz9dMWYnKkitLIQVASmjLxrGLEZAELwiBdDykh3khqKbjOt/Md5OJUo6XhKVmLieFLEmRgBflvCIF4kt/xcvhSL3kLupWJKYIYkUKha3EI9mVRDwKUG1IIkgQ0jQ5boZPx+fVNICplyzgOJ7JZw/ucHnO5TioQwlXXudpiSgfax08f4ufOngOCUewml34mr5kzZeThtNu6qmIo1bTyflsNmukFtSwIq9Gjj8RiQp6JR0VkmVImCnQAD92xvnwulUBiPPUccxSLW3uifL9ajUJyflKMsHhH7DNEAZcELUlayXNkS0Ptu6v3W8Ph1+7AoHR/1zBvcOxu9BjYwsejXQKsOuPsHHsPl1k3//GsSBbBaNA93XtK6P/gQCOh57NnvFjc6C7ai3NgiHdqnb/Xbo1u4iGCWzsAY6Nc6e4GxyHImuu8+06XypKRtL0CirMQ8tYWRfIXpIq9td5Z8UodeQSnrcK69DR2lXZ5sngWmSfdb69ztNoq4QqKaq8kfyOqOjRYCAQigY1Xfz30TCkvCAEwxExZqqyFE2qUlQJCXMDQwkBnlOe5uVoSInx2cB8KmbGgqj8eCQRC0MWYoqohOVPSnJQicfjSjCVDMX/FpRQb0OURT6sp+YsPQJiUNJ2dzfINPGWtZDyXVkJxtR0OqxZ2ZQeFiNaJKIEwpoa5GQmgz0YcmEuweW4Eudwq9zbUBYlo4XC6LSrHq5CbqEbdTsoGhew39EKmtwySrKKxx0mHAndzkha5lFJ4Bm5ZP6RW5MiQTH+qVBE5mEV1FtSIBgWKwuR52D4mYsX25JmKY9cjRqxUFTR4hvBWCQO+WDOjKW1UEhP5VNxGd4Jr6zwYkhWlYwUCgWiMVGMyMEAX3tpNIThB7QPh6PS13BRGV0UU5oqByOSlQwl0vNzeiRqZuJxTpyuNYRrtXClbbQRXKFDa+2iThFLTgEe4/KEUqeFK0KnwsZKSp7T9RAr2t2mmZQgGYtsbERi6d6GGtf+FIavbm/bOCzKR9OQuxhLBHCKYSsa/cdARAVPXT6JqhMU7Ts01dH+AeSMdAqE9Fwq/6yixlFP0Zhmzfv2i369C7e4OTwoFWMgyZoNa4Bi1erggtdCg64DDL+nRR3UcErf01PU/JbxPRdSsKM4UW30l3oqpSNWpMzRHvT0FHnDeO0Wlxnr2eWWuRb2dkpo0fhFo9eSZqvQ7JJVl6BTMBxUsodfaq2ZfRi4Q7eHxhqCTdriU2p3arW+6+667uZkB7BxXTy7z0a6IWV0sL+P4/DPZX9cYDwv8tc5nFUDNZKUilWSs2egVRXqpJLuGi68aaICilLSbDJUR8BLmiQY6Nh1Gz+fSuujAz2d1nfcbT09gMaFBn7eB3rUVXVddaP6jmnbS7b9vn1fZLt6yk1/rtJoXGw0vh/VAfSMrs/iQhDRdZFFnjedEX6bOfDn5bDAg4gLl6HWq+HnUyl9dIf00ENYfzwkVVAP23BqaekUsO1uvlbbcN3L48ns6+myLJfTH1k6CXByqU7bCc4foD1EUHMcTJ6CoJ6QHdnxHM/yLBm4a0/y/JPX2DZknzs3+cDOpBe3o7+fOTPBygF3l56Ct9kZDO4OBpN+F1zqR7wFdzCg7yFu9/xzG+DsDwb9w2sGfmRC3IXBYID3I1mO568x/XKegfCNYVxD/2qa81CQRdJjs4tAM9kZAnePQ6nUanoa+v3Rv0V10sxrKmt2am5aB66W0s29baayzFh1GX08jz3YxOeh/zgzRk2eDbu77nBqtuDWlNA9jo7RQqfXXiSkILGC886tH9r3uOG3/WYmvoRoTIJE7/z61hZGKgix5lBGFzFeiUx+qCW46A8qTgb5Yzb9MShHvNHvs3Pv9EdMnmPS+Qop2oItdupDb3gO+XQEWxyDj8IZeQ7s2V/60uQDWzMHiHwTffCchJivcjpnckWuy50g3WxAhwKxgTfqOJbhLQMdzhidlTRivFRcFjrIrXKC3JF/OXvu0YXbj67cfrR54dGFkwv4N2OLx0B4WpCEpwRe+LAkPQ2Clf1uNbHcXpubW2sXumudfL6zNncsk8nszxjqfwOyqod4/sGA9LD0cCDwEEinqoxjBMfz/1XO4NLcPPpnmVtAH10mHFvmqzHByAlmc0PA6cvLYPhCISchEXdYC/u88K1w+E8CAQDhW2JY/GaA/5PP9B4sP9iL1eu/gXv66dOnl9kRCCAFbsrys0Lo4wEhcFMQbgYC4g+vu53NzY5bzOWexd08ItmL/uGsXgYoWw6DooQxEw2xSqjhFWyAvbRu9PcIqYAsvIc4tLnJ4AiBgKOYPPX5JK5wCbVzmkMmJCLM+MROJV34SpF9KGSsF89uQBX15SA9ccyux3DJmyivVMQLZaLApoW+MIsZj0q9RV2D3LHHeD0BV07z1ol89SXh0nlZDp5/fzBtyO86k3ICTucZccFq1Pn0qZL5ZWGlKYuB5UuSacwo7/f4iNg8HzLW3xO91LKvBPXkydDVDB+PJYIgltc/DnL82JqUOHNDWqslj4lm6j5xyYxGw2KIL6we8jKyawFloeC+Z8WQw8Z4o+XB5U6v84PXe6+bRs84cjBzHdl0hnil1uocQYCSQ7dyZKMFg3vc9jbTAUJNLY83Mnu3ey4DFkQfPLH9e+PO6Zx2ESuDDMk4bxoTfgy+diFVTuFnU6dt6nG/2fOb9PgkjFv/3lN9x5CZHEF54iEd/B7R1jmKoEeh/Y9dl0CBH3Nlil0Zsj7kqo5X6iTYbYqSbOCNGc0pwa6LiLDV3+/3pxHIhcHuFva6o/19RNlxaOpPbPqd8Cz6HVfotPCWFAI7ThVvOg9InQyw1kJno0Y5oSYWGifXvnp2Maaf4qG+2Dr71RmsqmBb8HWC19O0KB3LAfEPy2jJjIsRAcFk4A5B8yvNJiwU40rc1hU4ITe3CLmHyCrw7M5qreoAtONKZXXHR/WJDJD34B4huWa1HK23t7fXA244vMcd2pgvpziXmtGnwySEjjNuJ9rsn70GPf6Z6x/8otALvNrztfnlHlw7e/2ZJ3vCFz/42Ve5w2ebzE7exEruArGNi42P+bRjr0wcpbEyJitTjjrgong9YVyW5KUCyctqechWxYLB/i2UnYWGseOTnh8N0qNvQG10QN87d+641zEcM1NOwQCNr+bW3H7t+vXDfGpAjCJhkAZpbqcw1Znse9puWMmUy155NxzJUgsw+H4A23Jm76bf4hon6z1gPlfFu7GYPkU8B3UrlyiLQgc0PMoNOpgXOXt3iReZ/SGzr7rLWNIADz5oIjwO0/rQR8Shnt4h+9PTvV5ar4Ft0eMCU38JouZyiP9cYh2IlxerFnILNJ4uuruJIpPAoEDesTQUGJnVzpgofJ3kkiLfT6dH/9xu9M9vjvYBJwIRn2z8kQ8MPhaA+0/txub576NbIDog+ZnBGn8OnOdnBsVqBZ9ampmFqNEMtN1UOZ1GtzcmJJWgf7Tb61zvkzDw5EcO+3HMXTyzyTQ1lfEm6muZZGwwHyE+4wJ5n+9JFXLCsZvPj6kxjekf9Mha9QMm5R5s9nozPYBEnsmbSdvtu8PZ4ymeuMgVDPZsxCbUqlfyDEzzZAN3O/1bSGgzZTSzAZQzxG/dW8hia3hw6xb215DP3uKmtr3JcH2MdZVCpyCjchI4e4etALF5j/KkPimkv7u7v4t/Q8wqoDYc1mZyhk20uQzG/yUfUWjNFnmEn8SJk2TN+rGdicvs9Q1S/38ir8zq+sNHGuj7Abnf9xOF229gmlPGeWgLA2RXCqIJ5/m1gVNQyIHs4QJ7Y3UPd4bDu7S23hhxe6SLMWe496/Mpjem+G+i+qQqxe1ql3JRs+mxiE4br21a3SaGCMOUZJOFdYtKFixmsFgBD56W5cV5CMZAUfh4PF6OCOHKKg+GIASzufTxdC4bFAQDYK0SBTnYexD4J1lMufB+k5fFslwQ9GgowCfAEo0g754smaJtQiAhy4kAmLZolk66fNheFWXefP+Fa0+OfRPn/4foFxKTBmlYRrbfRfa1AbIjEpM1k2DvBQGCox/+dqv1W9A+2+2eje7tYSbwdlUc/cJXL7Z++/Vqt1uV9UOs3kfZUNZOeXHHt3zZKGFu7CesFbQcoWNBP61TOBuidAFx4x7X7xu3occgxh3dTaRSCTBc9x63159gyT8w/FrhznKPcO9G7TlkJ0hvPVbwcDDW4aOoINRqeqy18BgRGXfWoYMKoapkp+11Efwsk1JEyZIQ/TptomMY3SwqjXgsy0b3bBmt/9QDoVAgLkuKrChioTAwVqxCvYZ9fFhKHJ+zdO/4fecgdVVLhzRFNePpYFyQ1WKyUmtGYrKiFURlPvvXq/m1tfzqF2KBiBYVVTmoZ+MpLSokInrBKbQgJOLIYCimlmO5JYD1arZ4yYjl5k1dS8TzuaARjn1Lq2RjiWggIAmQtJPpF+iGq1MO+yraNOVRVGdFLVKTzGHe24YXC/2ChJdhk8u9+GIOLufzoiyL+Xx+M3/7dn5zaguEkTHEyCXKMCiSUT2D3IPqGWjmfrZv+aCJMUgyfOrTdlodSS5hDOl6LdMCDNwIJQgp4LcvYHjqlstf9TO4Rd7PrPlFCLlhgLAbwkCCo2ev+ijQFd3y14lW7IQjfiYeCV+eXBAac7Eh2hrNOctqMGOu4rMSwY/nSckraS3o3yEcoc1jeE9dUa7cuQM7k8QfkAGOBtStKz2Y4R0u4x2MR8IMOvmxd7rD4s+bUEYw3pRgjnV2AMe5U2TFaIdog+tgNZHxo0xx/u3qMj4PQcLy/Hp4kp0yJDT5Zb+G7Fv138eL83N5KFs5W45HTqzXPVQz1aTfIjQEt1ps8Rm7kIhBs1IJxmNeo3vca9UW3u3yaVgoL1ZR3ivlFciX54uyLKiRObBFSnxyTjovB8UYdkAh22gsQG/1+Crw1rTm4uJehqpSVGkihmO0On6C48M7hZuSR/mOQZ5EdasJoW1Xdw4O3MHARdcfkPiJULh32fawd7/mDg3Dh1+ffujGLdoYs93/rzFXGPveZ9BGFOLLCWYjNkhySyslWkwKCDX44HaVYRPbHSSt1IIJqZMPPzw8L0JwoVBrw8MJK25govs2FJBVsvBTGP0HBCtqFo6v/trn5nK6ElK+8LXmbG59ayY+U7Uw72uDcikB82eqqhNLRwLQqeBxAr/yXcpIPmtfsYHDzTe3tw+2R89dsa9844p9Odffht726Mt44hv4dWjoz+O50b3LeDjhN3fRJ1TM6DmKYU3LozRWLlme6MhENIqOTIbpPRt6S6OQyTiN+94ROrPZB3ezv45dZTtTa2HX/vIaxAop4N92enu7tr2Nh4lihg4neEQ65XF9YWTYHEVoKpzQWwXPgW+NnnjtGzd7Z56HF27eHG0+/zz0X9tix5mPP/f88zP8nnJTpIEJKoRPde9bglxyxlYxsRfk6SteqwfDqyFeFPnQ/XGozlcgfjooiKIQfCiTeQiGRAtuivy2EEinP/CJT3wgnQ4I27yY3tqazYl7Y91wRCvYv1Ho9PyrGbFwe7UBciQfC25xB3Slh/xqQGnBfu2QT97CNUSJrcwi3Ckkdxayt7GlDq8TGR/nF8Y4dxjj4wJll5TeEMknayQgd5g/Es2vwzjZJI+F65T1ANhLNiAWQp7tsT7+THPlPgDjZUyEyj+wbNt6mdD5F3+R7bLO5hmAM82Xp/MeMBmgTWolKoYPtrf3tg3YHN1hmp2sLcglUT80mXYVM0up6BCGFDqUn/vJ1hdzV3OlY1A7Bq6fjP2SZSXP1nq92tmZfDXrMxi0SkJIF7mZxbiZx9C0KsFSo1lqhMRASjTVdjLFJ16+mcxCPHpJsb7QKDUbIUu5FI1DNnnz5QSfSrZVU0wFRG4iS/K3+6acr46MoYHMgbhEkr3MWye24/jAbMaAoBpP+0Ugqv3QG0+zNcP7Lp0EENKSGVejihhIxOerKwv1ZkjmQQIpaZ0/d/wSwMkVLSOqgZhsF1gJgRG/t7wvrRZi25pqzWuZaiJuAnQWnWUAr6LOIVdMi0K4kWpf5uFs9zhu1XBLzUVCrAAx5Qwke548o9IHZph7h7zwYMr9qZaN1kt5rNhiODpNPWFA7yz8794e3KklUixJxqyitu0O3P3Xw+5GrZafyWPRHyrsFYZB8aIFu7dqt/CzT5tb43H/Aj9DGSpQpDOSMZQ3StKj+GhanSqLKGNrbTvrAD9wLiVUBfReqaDpiY0y6jfz0Ht5/j0P4haOoSVBNSp/Opngs3MRpTtPDc8/JvPvvgyXt3hqlEjUm83fhv66EwXDcwyWsHhioSNbHVaakgfAbW9TtulCjWpTwHaN3mYf04crxeFkZ6bGTbWxEt2B3lGhmSAa7uwMTmwE7weuv7PThxMrgxPnuKluKEeZ820NkbU0qSVOwRVNyDjzjvDpPsNU7wLABa9szx1rXbzO89dhwFAVIRUudrsXfWC9ceHCjSO4GOPShxWeycskwZE9JNJWS55UdVgB/tqjj2Yvv7tS3XpwUtDxT4z+7MSJG6e2tk69sZYDmlOyNNgjw+jd44ZDOPJslbOZz1vJGC+V/Gqp71ddqvxS4kRokogm7ZKPKmffzvNvP9usXlu6Ngf826GPfSU7GU1g2zyziOdwBMzh6SqOPfpuKEUYOH03ZJEJIQKOK3ctB7v8+qv/YhFv7cPOxx5B2WbqWi51qty9mvT2Z/bx1LgidALFnNRzFjKl1cbedM9dXpvaPaulVSTZ6bYdj/RHQGckLZngAtEC10zZCgEgDFLa4wCPaylW1BnvZKiTajlDUM9IqnRGBcaQM/JkF+iEzJj24drpXXGaK5DPIRWguOc5HbJpel1JNAkTPc+p0ptiGCxt2BtRbWkb/5a06LcXF3Xl21+xe4q+uDigU73+5jZZdvQ1N/raur0edacYvsneUVD9jrj2YL/f66Fr7GDyzr1xDNoFcSPYoUHQHx3s7EBtkt99D/4GMTbPrSLOXmESw+hUYg7o/5rEkkyvYxlml+wFs04kxgTtTqlakjCk+XWceUKMyatJa7ID3xR4pIyjg0RKDIekyFIxNQwr4WGquBSRQi+plFnzQgCkkHF+yX8Hunj+lL1o4+dpv/kO8Lcp3t4WZCWsFtSnljceFt66sfwU7oeVBihhTLAFnudF8yVykJdM8byRzdYyGcNvaJ3yvXsoFAnOcAZX4za4B7nr3M9yz7FahIRRo9qhuLHBt5tGDkxMV+tAEGgx/s9y3eqbdqIttavUSb8qwRhIP6TB2yXZYRsNj9JCdn7FMr0m3oVeUlQpMBExnQfG2X8EPP5HcIMfhQfAdC0C7BD/wrTl+Tfrc6lPAAhgD23reILnBTof4JcBNygYmQ8IIOF1d0VDzZji6eWwFRIh/DtFZy9Rng8FJT4QDM3rlwo5ScoV9EIGRJCymfOZKP2AQArKUdx/s85QkjoNo3sMsAuOdQ1stFgtDwIvQr4Ww3mBEA6nEzwfSKTDYswUQ+H6OkiiIH0nDHzzaL0ygujrcmtveI+rksCkOsmbpMoC0/iYxHz0SIUjbwJkIRK48jNiSJDED18VBSsQlRaf6EhKQJLXPtbCrL776XZQFYPBtV/fkAOh2NGXBn8uCkI9DSLG8ExLiHQlQchEETpVhddidiDatcMxXo6rgq4UxVgscBjjKY5jJNN8XkkeN/HJVxEfWGaLfBJtqI2ORL9iIIbsTbL9/qf16CuS9HlZk16JKht+xRV7NPnzkvQHiv7pkDI4Ul+beQeOGQJMyc8U35kkZaQAlgfchRs8i0u0PfLWZMvGGDY5c+HG4owsXv/QJ7dsn5P9LzwFz9A7AZEKEiWqdrZYYVJiPAuJLuS7zePlunT8J34CkvOJMtSFRuPJ45GV9vUL1+czqKQ10Kf5+ONcHVtJ7nr0azOWYyPPc8iJivSizqLaCltSqeiwONzpwr6VyUbmbKWQqDR57x2FiKEZupOLKMFgcHHePG5HwmuXn/oozMHZsKDlYlJUhZVKOCw0FhKNihKG/DJqH2CuCFoSqhD41Z+MJCb6+x78AmV1OCepVEQFlYoYRDyyP9P/BU8Xe/AA9oWrj5yszJUSpphN5nI1oxmJiqqmdvhAPh7PPXoGyhs//XPnPvqW5Fw2W+bFi29Nnu6bFfkxnvdl+V8sTh0j1KX3AcRrLcZrPcZrWZyS2CtMItWU+XmwG4si/MaUFIgYem1ZXry6XClkq8Vu9HTmXWayeN+ckX5VaCya5oJiBflkIFbUFlfg+CP3aScqztOP7f5SUDEut8U3+F4Kc1n6NUeHCAIuGOEOnz2u4SH5w2DmsMzW6mC/QZQBOWe5AWpKAvsJyFp6Em5cWHvgdzc29reNfn/4U5l8vXLaHL3/3/LQKM8ZqXDUsjsrZYTCHFKmPP/AcxvrH9k2hsPf/KkoZj1Gz4RfmYmjEYyjOZoRxehSh9yDvXYaF9brIOJkNBlc07ZNyoXWHgB4YO3CDYAbo1f6w+Egb9ftPBGLe/iwtbUH8JnXL168/j5kRuxHAuLM+jWUwDmMDEfQR8RlohyKjpcDSSCPRQojoVGokONlx2OHLvgVB59XUDUTY4rHys5e12kfQaTR30H8WmPt69m5E2u8HQzJUhCCupbT9CDISbt2zmTHcWXuba3qmTSv6pGgGA5KiQsWQGtxLQ5HMOq7tfJ/p649H/zKi0IEjR34KMYI/KjAP/zMX/DscKEOmRRAMm1GwnOakkv0/uJYq7s5d2chG5nh349wK/SLL/qBF9XUHRft36/kUqBK5vy1UfRDK2Q/nex4lME7lBP/pRxWUnJjpd1eacgpJSxjHOLlcHQumOuenOm79/Ng8HZEIecTJCVi84aRyWOo5ucVRaS5YzwTFWV+3P+hJ0/h7P4PUrWLBQB4nGNgZGBgAOJ7xYy28fw2Xxm4mRhA4GJBeDWM/v///00mNsZVQC4HA1gaADgIC/d4nGNgZGBgPPD/AIMeEwMDw/+fTOwMQBEUkAEAe9QFHHicY5BgYGBiGMWDFQMAz+gA5wAAAAAAAACQANoA8AEGARwBMgG0AioCfAKoAvQDPgOEA7IDvgPMA9gD5AQcBDoETAReBHAEgASSBKwFDAVeBX4F/gYaBkgGdgacBsgG6AceBzAHXAd8B64H1AgOCFAIhgjECOoJDglWCXgJ3AoGCjQKwAriCzwLbAuaC/gMQAx+DLoM9g0qDUwNiA2gDa4NzA4KDhwOQA5yDtoO6A8SDyYPZg+OD6gP2BAEEBYQTBCOEMoQ/hEQESQRmBJmEswS2hMGEzwTYhOsE+IUJBRuFKQVJhV4AAB4nGNgZGBgyGBoY+BkAAEmIOYCQgaG/2A+AwAhJwIOAHicbY89bsIwHMVf+KoKUoVaCamb1aFL1fAxMHAA2BnYQ3BCUBJHiUHiAj1Bz9Az9AQde4YepS/mrwwttmT93s/PtgxgiC94qIeHW7fWo4Ubpgu3SUPhDvlRuIsBnoR79K/CfbxgLjzAAwLe4HXq2+5hhVu4w5twm/5duEP+EO5ihE/hHv23cB8b/AgP8OzNq8TqJDR5tdbxMQ3KJjew0ZQmV1N/0riVznUZWL1T27OqTvHM2khFpcnU0uRWp6lRRWkOOrT+3tpiMR5H4v3QZKiQ8DeaawiDnHnNFOOIlD8ur+z/NxumS7POClP4mFzprZhy1w3czo7dLc5cK5z45ozWImKO2DHISEt3tm6nnIamcHsHmpDex96dKrDAmDP60/fd69kvhyxikgAAAHicbVNVu+M2FMzsGnNz75aZtkwpM21hy8wMsn1s64ssqYKk6a/vsZ3cfakepJnj+Q6M5MWFxbzSxf+vfrHABVxEghQZchQoscQJVjjFGS7hOlyPG3AjbsLNuAW34jbcjjtwJ+7C3bgH9+I+XMb9eAAP4iE8jEfwKB7D43gCT2KNp/A0nsGzeA7P4wW8iJfwMl7Bq3gNr+MNvIm3cAVv4x28i/dwFe/jA3yIj/AxPsGn+Ayf4wt8ia/wNb7Bt/gO3+MH/Iif8DN+wa/4Db/jD/yJvyBQoUYDQosOfSYG8a/RqbBW0VI4Z3brxuz0ASpqw8kMnez6UMw42qISuqnFYPOKeqFrKitlOmW2UieVMZuiFop0I9ySReTEWqiQzZAP1iv+4CjMxWY4FZvhXGzG0SYMRhaoM26f1j3VmxXvW2f0lOCcjClOj2RKsjyyaNNaGU8ntWnIkh47yg+Yz2EgHYrGyaqqFBXUyDAqkhEUpJS0XvqUeHxX0D+BnBZq1YqaxmlHZXEkHPVh3Rq3E65JWqIma5WsN27FsUFwWi8bOiexkebkQOpehLMD7oRS5PZHnRxER0edknpz/PB3NIEuHYgPYjS9Ob3GQ/RH6ZbrmqyToY/VWWf4vsgqsR+7X16j5zD6tCd2vpSa83RODJm0vdGUbqgSVaZ4znYoxmYmq0YwMfZM58oIPrpEGWOTQUiVDRyPQ8JGx3SQmtNbYcmV016zw8yjp4yZ5yc5lSqt1Gw2+ZCMvRXjpuTEok8ce5c5vkERUj7UPh+VxtHK0ZZcpUWQRrNiJ3WTeR6m7kvf87MaG04nlPs+ti0/fr+Rdi144qacYCXqzdIr9mzSLb2J/OSViU3urQmy3Sdcy15ka5IgB8pCHCrl8rCTgVtOtxwzCf8QtNwaFQdam7Ytj1CXO+May/36fG9iiBUtFv8BK0Vi5QAAAA==") format("woff"),
		url("fonts/siteicons.ttf") format("truetype"),
		url("fonts/siteicons.svg#siteicons") format("svg");
	font-weight: normal;
	font-style: normal;
}

...
```
